(function Test() {

	var dispatch = {
		StartTests:StartTests
	};

	return {
		dispatch: dispatch
	};

	function StartTests(com, fun) {
		var that = this;
		let pid = com.ModuleServer;
		console.log('test::StartTests');
		AddModule();
		if (fun) fun(null, com);

		// test Cases::
		function Query() {
			//TODO: load test cases from json
			let cmd = {
				Cmd: 'Query',
				Filters: {
					output:'GenPage'
				}
			};
			that.send(cmd,pid, function(err, com) {
				console.log('test:Query:Callback: ', com);
			})

		}
		function AddModule() {
			console.log('Test:AddModule');
			let cmd = {
				Cmd: 'AddModule',
				Name: 'testModule5',
				Module: 'UEsDBAoACAAAAAeiuEoAAAAAAAAAAAAAAAAHAAAAY2F0LnBuZ//Y/+AAEEpGSUYAAQEBAGAAYAAA/9sAQwADAgIDAgIDAwMDBAMDBAUIBQUEBAUKBwcGCAwKDAwLCgsLDQ4SEA0OEQ4LCxAWEBETFBUVFQwPFxgWFBgSFBUU/9sAQwEDBAQFBAUJBQUJFA0LDRQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQUFBQU/8IAEQgAQABAAwERAAIRAQMRAf/EABsAAQEBAAMBAQAAAAAAAAAAAAAHCAIEBgMJ/8QAFAEBAAAAAAAAAAAAAAAAAAAAAP/aAAwDAQACEAMQAAAB1SAAAAAAAADOZazgZSNogAxeSY8wemP0qAJUY5OZ1DpGxC2AlxOCDHxLsUkrAAAAAAAAB//EAB8QAAMAAgICAwAAAAAAAAAAAAQFBgIDAQcQQBEUIP/aAAgBAQABBQL0iqc5c+UPBnAbugCQLh+xmTmt/FMTjrdHMvnnLLnLmWz16qXzTUTlUfrc8AN7OgHpnUm60T7ygZa3TuKpKBmb4rY7fUEu+mBsgjYCgBzEhKAzYh6X1fUjorfKF+j/AP/EABQRAQAAAAAAAAAAAAAAAAAAAGD/2gAIAQMBAT8BAf/EABQRAQAAAAAAAAAAAAAAAAAAAGD/2gAIAQIBAT8BAf/EAC4QAAICAAQEBAQHAAAAAAAAAAECAwQABREhEhMiMUFRYYEUIECREBVCUnGh8P/aAAgBAQAGPwL6K4yzNJGszLyXPRoDp7Y58TgabOjHdDh7lqUCMbADu58hjLjz3grNZRBWiPTwlgN/P5cwCsGHPfcfzgheo41OMqeZxHEtqNmZuw6h8nLo5W1yvwA8Yidt/bFeWWAWFhlDSRP+rQ9sG5WqfCJwBSPFj+4/7wxXu2KwtxR69Hl6j1xauQVhVSZ9VhXwwtbM8pepWWDad4nUsw08T7/jBpmUlSqE0khG4b10wv5VZdLSd/iTqJPsNscL5XO/rCOYP6wETKbKnzlTlj7thzm9luew6UrHZPcjfFjXNJbdRk0igbUBd9zp2+i//8QAJRABAAEEAAUEAwAAAAAAAAAAAREAITFBUWFxgdEQIEChkcHw/9oACAEBAAE/IfhSxV7U0Achk+70WnKAci+d1eRu46p7f7FByD8ZgOPDl7R7Z2ANF20RoHbgpEkrSUpSgBL+y44Lmpkm3hVsEw+45/ZU9zexGnBu4dBVwuBxKSCa0M+M10EVpBra3ea1MydAgCbNyWPV6e0y6ZBIJuks4Ku+B9lNz0PNL+FZx3nSNlwR+ArQJxnNUS7R1pdDkw9yTZWCSMvwv//aAAwDAQACAAMAAAAQkkkkkkkkkEkEgggEkkEgggkgkgAkkkkk/8QAFBEBAAAAAAAAAAAAAAAAAAAAYP/aAAgBAwEBPxAB/8QAFBEBAAAAAAAAAAAAAAAAAAAAYP/aAAgBAgEBPxAB/8QAIxABAQEAAgEDBAMAAAAAAAAAAREhAEExEFFhIHGBkTBAwf/aAAgBAQABPxD+kjUHQkFjAzGlYQhqQIJK7/k8Bp2G06FoFoax7ABVAoj4EF+bLNRg6MgeqzmxcYqUD8Kn3Hj9AiVX/Xi8tHx+uWiqKPFdGauHlhww9RIppc61EDCUvycJBb0ChgxYjTcR04QbSRVsYWeS9rok1QRMexlBfwqAPLwxFQ4BMyOlxUkk3VktZApTPD6hRk0i4uscUEx3kbOU9/QEOlR8IeHbTwSe9Z+zH452gLAvdhfvlJgjvxfYjgBu2JZpJJdAhDHRUM4fVP4//9lQSwcIR0A2/j4FAAA+BQAAUEsDBAoACAAAAAeiuEoAAAAAAAAAAAAAAAALAAAAbW9kdWxlLmpzb257CiAgImlucHV0IjogewoJInJlcXVpcmVkIjpbeyJwYXIiOiJQYWdlIiwiY21kIjpbIlRlc3RQYWdlIl19XSwKCSJvcHRzIjpbXQogIH0sCiAgIm91dHB1dCI6ewoJInJlcXVpcmVkIjpbeyJwYXIiOiJQYWdlIiwiY21kIjpbIkdlblBhZ2UiXX1dLAoJIm9wdHMiOlt7InBhciI6IkxvZ2luIiwiY21kIjpbIkdlblBhZ2UiXX1dCiAgfSwKICAicGFyIjogewoJInJlcXVpcmVkIjpbIlBhZ2UiXSwKCSJvcHRzIjpbIlBvcnQiLCAiVXJsIiwiTG9naW4iXQogIH0sCiAgIm5hbWUiOiAidGVzdE1vZHVsZTUiLAogICJpbmZvIjogewoJImF1dGhvciI6ICJBbGV4IEpvaG5zb24iCiAgfSwKICAiaWNvbiI6ICJjYXQucG5nIiwKICAiZG9jIjogInRlc3RNb2R1bGU1Lm1kIiwKICAic3JjIjogInRlc3RNb2R1bGU1Igp9UEsHCLMOXUaQAQAAkAEAAFBLAwQKAAAAAAAHorhKAAAAAAAAAAAAAAAADQAAAC90ZXN0TW9kdWxlNS9QSwMECgAIAAAAB6K4SgAAAAAAAAAAAAAAABgAAAAvdGVzdE1vZHVsZTUvc2NoZW1hLmpzb257fVBLBwhDv6ajAgAAAAIAAABQSwMECgAAAAAAB6K4SgAAAAAAAAAAAAAAABUAAAAvdGVzdE1vZHVsZTUvdGVzdERpci9QSwMECgAIAAAAB6K4SgAAAAAAAAAAAAAAABwAAAAvdGVzdE1vZHVsZTUvdGVzdERpci90ZXN0LmpzLyoqCiAqIENyZWF0ZWQgYnkgYWxleCBvbiA1LzExLzE3LgogKi8KUEsHCN68bWcnAAAAJwAAAFBLAwQKAAgAAAAHorhKAAAAAAAAAAAAAAAAGwAAAC90ZXN0TW9kdWxlNS90ZXN0TW9kdWxlNS5qcyhmdW5jdGlvbiB0ZXN0TW9kdWxlNSgpIHsKCgl2YXIgZGlzcGF0Y2ggPSB7CgkJU2V0dXA6IFNldHVwLAoJCVN0YXJ0OiBTdGFydAoJfTsKCglyZXR1cm4gewoJCWRpc3BhdGNoOiBkaXNwYXRjaAoJfTsKCglmdW5jdGlvbiBTZXR1cChjb20sIGZ1bikgewoJCWNvbnNvbGUubG9nKCd0ZXN0TW9kdWxlNS5tZDo6U2V0dXAnKTsKCX0KCglmdW5jdGlvbiBTdGFydChjb20sIGZ1bikgewoJCWNvbnNvbGUubG9nKCd0ZXN0TW9kdWxlNS5tZDo6U3RhcnQnKTsKCX0KfSkoKTtQSwcIGyYOzwkBAAAJAQAAUEsDBAoACAAAAAeiuEoAAAAAAAAAAAAAAAAOAAAAdGVzdE1vZHVsZTUubWRQSwcIAAAAAAAAAAAAAAAAUEsBAhQACgAIAAAAB6K4SkdANv4+BQAAPgUAAAcAAAAAAAAAAAAAAAAAAAAAAGNhdC5wbmdQSwECFAAKAAgAAAAHorhKsw5dRpABAACQAQAACwAAAAAAAAAAAAAAAABzBQAAbW9kdWxlLmpzb25QSwECFAAKAAAAAAAHorhKAAAAAAAAAAAAAAAADQAAAAAAAAAAABAAAAA8BwAAL3Rlc3RNb2R1bGU1L1BLAQIUAAoACAAAAAeiuEpDv6ajAgAAAAIAAAAYAAAAAAAAAAAAAAAAAGcHAAAvdGVzdE1vZHVsZTUvc2NoZW1hLmpzb25QSwECFAAKAAAAAAAHorhKAAAAAAAAAAAAAAAAFQAAAAAAAAAAABAAAACvBwAAL3Rlc3RNb2R1bGU1L3Rlc3REaXIvUEsBAhQACgAIAAAAB6K4St68bWcnAAAAJwAAABwAAAAAAAAAAAAAAAAA4gcAAC90ZXN0TW9kdWxlNS90ZXN0RGlyL3Rlc3QuanNQSwECFAAKAAgAAAAHorhKGyYOzwkBAAAJAQAAGwAAAAAAAAAAAAAAAABTCAAAL3Rlc3RNb2R1bGU1L3Rlc3RNb2R1bGU1LmpzUEsBAhQACgAIAAAAB6K4SgAAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAApQkAAHRlc3RNb2R1bGU1Lm1kUEsFBgAAAAAIAAgAAQIAAOEJAAAAAA=='
			};
			that.send(cmd, pid, function(err, com) {
				console.log('test:AddModule:Callback: ', com);
			})
		}

		function GetModule() {
			let cmd = {
				Cmd: 'GetModule',
				Name: 'testModule5'
			};
			that.send(cmd, pid, function(err, com) {
				console.log('test:GetModule:Callback: ', com);
			})

		}

		function GetDocumentation() {

			let cmd = {
				Cmd:'GetDocumentation',
				Name: 'testModule1',
			};
			console.log(that.Par);

			that.send(cmd, pid, (err, com) => {
				var buf = Buffer.from(com.Info, 'base64');
				console.log(buf.toString('ascii'));
			})
		}



	}
})();